stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    - params.yaml
    params:
    - data_collection.test_size
    - data_collection.random_state
    outs:
    - data/raw
    - dvclive/params.yaml
  data_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed
  model_training:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - dvclive/metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
